server:
  port: 8060

telegram:
  url: "https://api.telegram.org/"
  webhook: ${BOT_WEBHOOK:"https://0c52-46-233-221-184.eu.ngrok.io"}
  name: "CarFineSearcherBot"
  token: ${BOT_TOKEN:}

gibdd:
  fines:
    url: https://xn--90adear.xn--p1ai/check/fines
    screens: ${SCREENS:C:\\projects\\carfinesearcherbot\\screenshots\\error_}
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:carfinesearchbot}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    password: fine
    username: fine
    exchange_client: clientRequestFinesExchange
    queue_client: ru.arkasandr.fine.client
    routingkey_client: ru.arkasandr.fine.client.rk

    exchange_server: serverResponseFinesExchange
    queue_server: ru.arkasandr.fine.server
    routingkey_server: ru.arkasandr.fine.server.rk

    exchange_captcha: captchaRequestFinesExchange
    queue_captcha: ru.arkasandr.fine.captcha
    routingkey_captcha: ru.arkasandr.fine.captcha.rk

    exchange_captcha_value: captchaValueResponseFinesExchange
    queue_captcha_value: ru.arkasandr.fine.captcha.value
    routingkey_captcha_value: ru.arkasandr.fine.captcha.value.rk

    exchange_answer: answerFinesExchange
    queue_answer: ru.arkasandr.fine.answer
    routingkey_answer: ru.arkasandr.fine.answer.rk



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: ${LOG_DIR:/logs}/${LOG_NAME:LogXMLProcess}-%d{yyyy-MM-dd}.%i.log
  file:
    name: ${LOG_DIR:/logs}/${LOG_NAME:LogXMLProcess}.log