server:
  port: 8060

telegram:
  url: "https://api.telegram.org/"
  webhook: ${BOT_WEBHOOK:"https://0c52-46-233-221-184.eu.ngrok.io"}
  name: "CarFineSearcherBot"
  token: ${BOT_TOKEN:}

gibdd:
  fines:
    url: https://xn--90adear.xn--p1ai/check/fines
    screens: ${SCREENS:C:\\projects\\carfinesearcherbot\\screenshots\\error_}
  maxCaptchaAttempt: 3
  maxDailyRequestAttempt: 5

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:carfinesearchbot}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: ${LOG_DIR:C:\\projects\\carfinesearcherbot\\logs}/${LOG_NAME:LogCarFineSearcherBot}-%d{yyyy-MM-dd}.%i.log
  file:
    name: ${LOG_DIR:C:\\projects\\carfinesearcherbot\\logs}/${LOG_NAME:LogCarFineSearcherBot}.log

rabbitmq:
  host: localhost
  port: 5672
  password: fine
  username: fine
  queues:
    clientRequest:
      exchange: clientRequestFinesExchange
      queue: ru.arkasandr.fine.client
      routingkey: ru.arkasandr.fine.client.rk
    serverResponse:
      exchange: serverResponseFinesExchange
      queue: ru.arkasandr.fine.server
      routingkey: ru.arkasandr.fine.server.rk
    captchaRequest:
      exchange: captchaRequestFinesExchange
      queue: ru.arkasandr.fine.captcha
      routingkey: ru.arkasandr.fine.captcha.rk
    captchaValueResponse:
      exchange: captchaValueResponseFinesExchange
      queue: ru.arkasandr.fine.captcha.value
      routingkey: ru.arkasandr.fine.captcha.value.rk
    answerFines:
      exchange: answerFinesExchange
      queue: ru.arkasandr.fine.answer
      routingkey: ru.arkasandr.fine.answer.rk