server:
  port: 8060

telegram:
  url: "https://api.telegram.org/"
  webhook: ${BOT_WEBHOOK:"https://0c52-46-233-221-184.eu.ngrok.io"}
  name: "CarFineSearcherBot"
  token: ${BOT_TOKEN:}

gibdd:
  fines:
    url: https://xn--90adear.xn--p1ai/check/fines
    screens: ${SCREENS:C:\\projects\\carfinesearcherbot\\screenshots\\error_}
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:carfinesearchbot}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    rolling-file-name: ${LOG_DIR:/logs}/${LOG_NAME:LogXMLProcess}-%d{yyyy-MM-dd}.%i.log
  file:
    name: ${LOG_DIR:/logs}/${LOG_NAME:LogXMLProcess}.log